name: Build

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  PHP_8_3_CLI_TAG: ${{ github.repository }}:php-8.3-cli
  PHP_8_3_SVD_TAG: ${{ github.repository }}:php-8.3-svd
  NODE_24_SLIM_TAG: ${{ github.repository }}:node-24-slim

jobs:
  php-8_3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate PHP 8.3 Cli tags
        id: php-8_3-cli-tags
        run: |
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "${{ env.REGISTRY }}/${{ env.PHP_8_3_CLI_TAG }}" >> $GITHUB_OUTPUT
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "${{ env.REGISTRY }}/${{ env.PHP_8_3_CLI_TAG }}-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push PHP 8.3 Cli
        uses: docker/build-push-action@v6
        with:
          context: php-8.3
          file: php-8.3/Dockerfile-Cli
          load: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.php-8_3-cli-tags.outputs.tags }}

      - name: Generate PHP 8.3 Svd tags
        id: php-8_3-svd-tags
        run: |
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "${{ env.REGISTRY }}/${{ env.PHP_8_3_SVD_TAG }}" >> $GITHUB_OUTPUT
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "${{ env.REGISTRY }}/${{ env.PHP_8_3_SVD_TAG }}-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push PHP 8.3 Svd
        uses: docker/build-push-action@v6
        with:
          context: php-8.3
          file: php-8.3/Dockerfile-Svd
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.php-8_3-svd-tags.outputs.tags }}


  node_24_slim:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Node 24 Slim tags
        id: node-24-slim-tags
        run: |
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "${{ env.REGISTRY }}/${{ env.NODE_24_SLIM_TAG }}" >> $GITHUB_OUTPUT
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "${{ env.REGISTRY }}/${{ env.NODE_24_SLIM_TAG }}-${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build and push Node 24 Slim
        uses: docker/build-push-action@v6
        with:
          context: node-24
          file: node-24/Dockerfile-Slim
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.node-24-slim-tags.outputs.tags }}
